lbInstanceId: LB01
services:
  - serviceName: dummy
    servicePort: 8080
    pathPrefix: /dummy
    serviceProtocol: HTTP
    healthCheckEndpoint: /
    connectionTimeoutMs: 1000
    healthCheckIntervalMs: 1000
    instances:
      - serviceInstanceId: dummy01
        host: localhost
        port: 8081
      - serviceInstanceId: dummy02
        host: localhost
        port: 8082